### PR TITLE
#37: Create upcoming events view

### PR DESCRIPTION
**Pull request by lrowang**
PR for #37.

### CODE REVIEW

**Comment by lrowang** [comment]
Hi @lhridley -

I elected to start with this issue (#37) for Sprint 4 because it seemed more straightforward (I'll circle back to #30 afterwards).

### What I've done:
- I enabled the `devel_generate` sub module and created 5 dummy Events
- I enabled the `views_ui` sub module
- Wrote a behat test scenario and demonstrated that it failed before creating the "Upcoming Events" view page
- Created the "Upcoming Events" view page and captured the configs in a new feature and exported to code base.
- Enabled the new feature module

Failing local tests before views creation
casestudy 37-testfail

Passing local tests after views creation
casestudy 37-testspassed

### Questions!
- I created the 5 `devel_generate` dummy events by shelling into the php container and using drush. Does this mean these events/nodes only exist locally? Do I have to execute the drush commands somewhere in the code base so that they exist on repo if we wanted travis to test them? Or is it okay that they only exist locally (since they're throw aways after all...)?
- I can't figure out how to **create a proper filter that distinguishes between past and future events**. I have a `field_end_date` that is of the type "date", but none of the filter options seem to make sense. How would you go about doing this? 
casestudy 37-filterdate
- Lastly, I noticed that **I'm having failing travis tests again**! 😦  It seems to do with the staff role, but I can't figure out why they should be failing if I didn't change anything to do with the roles locally!

**Comment by lrowang** [comment]
Hi @lhridley -

Thanks for explaining the travis build and walking me through the date filter set up. I made the discussed changes, rebuilt and checked the report logs and am pushing the PR for final review.

All the tests passed locally! (Pasting the full pic here b/c we can't rely on Travis just yet)
casestudy 37-allpassing

**Comment by lhridley** [comment]
Tests are passing locally; this PR should pass pending the merger of PR #58

**Comment by lrowang** [comment]
YAY PASSED!!!!

**Pull request merged**
