### PR TITLE
[WIP ] Issue #5 contrib modules & update script

### PR DESCRIPTION
**Pull request by lrowang**
See #5 for questions!

### CODE REVIEW

**Comment by lrowang** [comment]
Pushed branch updates! See #5 for questions!

**Comment by lhridley** [comment]
Ro, let me know if there are additional questions I didn't address.

**Comment by lrowang** [comment]
Hi @lhridley ,

PR updated! I removed the [WIP] because I think this what I'd officially submit. I posted a change description and questions in #5 !

Ro

**Comment by lhridley** [comment]
Closing this PR in lieu of #22, but keeping here for documentation purposes.

**Pull request closed without merging**
