### PR TITLE
#30: Create "Latest Content" View

### PR DESCRIPTION
**Pull request by lrowang**
Hi @lhridley -

Got to the stopping point we discussed. For clarity here is what I did:

1. Created a new view called "Latest Content" (and dummy "article" content to test with).
2. Create 2 Displays. They have the same settings, except that the `Page` display has the contextual filter.
  - `Page` with contextual filter
  - `Block` with default settings

cs 30-displays

3. For the contextual filter, I selected "Display all results...." when _NOT_ in URL. And I can see that both the `Block` and `Page` are displaying the same thing when I got to a page with no "Visitor Type" in the URL. That's what I would expect, **so far so good**.

cs 30-match

<br>
4. **But when I test to see if the contextual filter is working but typing "caregivers" into the the Preview pane, the `Page` display no longer works and I get blank.**

cs 30-broke

### I've been trying to think through this and **these are my best guesses**:

1. **It has something to do with the way the Taxonomy Terms are setup** (like the missing machine names you mentioned earlier). Though I confess I have no idea how/why that would be!

OR

2. **It has to do with the fact that I don't actually have any physical pages created that have actual taxonomy terms in the path**? (ie, I don't have a page that is `mydrupalsite.dev/caregivers`). The Case Study chapter seems to suggest I need to create these pages for the filter to work, but even if I needed them, shouldn't the "Preview" work when I typed in "caregivers"?
cs 30-book

OR
3. I'm choosing the wrong Filter/setting it up incorrectly?

Combination of all 3?

### CODE REVIEW

**Comment by lrowang** [comment]
Hi @lhridley -

Phew! What a doozy this one turned out to be! 😜  Thank you again for all your help this morning!

- I removed the "tag" field from the "article" content type and updated it's feature
- Set up the contextual filter following our discussion and created the additional pages (the filter works!). Saved the feature and exported it.
- Created some new Behat tests for the filtering and this view. 
- All Behat tests are passing locally.

All my tests are passing locally but I can see that **Travis is telling me scenario2 in `latestestcontent.feature` is failing**. Something to with the "sidebar-second" region, but I'm not sure what it is. I can confirm the homepage does show the 2nd side bar with the same CSS ID. Also that **particular test is definitely passing locally -- would you have any idea why the difference?**

cs 30-local

**Comment by lrowang** [comment]
Hi @lhridley -

I think these commits addresses the previously failing travis tests (scenario 2 in `latestcontent.feature`):
- I enabled `fe_block` and used it to create a feature that captures the block configuration for the "Latest Content" View's Block. At the moment, this block is configured to show up in `sidebar2` of every page.
- Also, I realized another reason that contributed to the test's failure is that if there's no content at all, then the "Latest Content" block doesn't even show up -- and that means `sidebar2` doesn't show up on the page either! So I added some dummy content to that particular test scenario as well.

**ALL TESTS PASSING!!!!! YAY!**

**I did notice something odd: the `tag` field isn't being deleted/captured properly by the `article_content` feature**. Remember we decided to delete the `tag` field on the `article` content type so that it wouldn't conflict with the contextual filters? I did that, updated and exported the feature, and committed it (see 874cd676b966f01f9135fbf07d35ddaa9723ac88). But after running `make clean-data` and `make install`, I can see that the tag field exists again when I go to create a new article! Why would that be happening?

cs 30-tagfield

**Comment by lhridley** [comment]
Take a look at this article:
http://www.hook42.com/blog/deleting-drupal-field-saved-features

After reading through that see if you can create a hook_update_n() that will remove the field (don't use the drush commands to remove it).

**Comment by lrowang** [comment]
Hi @lhridley -

I wrote an hook_update to remove the field and it seems to be sort of working (aaargh!). 
- It definitely works when I run `drush updb -y`. I can see that the "tag" field get's deleted.
- But to double check, I ran `make clean-data` and `make install` -- But then it didn't work and the tag field showed up again! (And then it works again when I run `drush updb`). 

Is there something I'm missing in my hook_update?

**Comment by lhridley** [comment]
You need to use the same code in your hook_install as you have in your hook_update and everything should be good.

**Comment by lrowang** [comment]
Hi @lhridley -

Finally! Ready for final review:
- "Latest Content" view created with Pages and Block. The pages contain contextual filters that have been set up as we discussed.
- Enabled `fe_block` so that the "Latest Content" Block's configurations could be exported.
- "Tag" field deleted successfully.
- Behat tests written/updated and passing.

Many of what was covered here will be needed for #38 and I'm holding off on making further changes to PR #61 till this branch is approved and merged. 

Also, can we talk a bit about cron and how "batch ranges" work tomorrow? This is in relation to the `field_purge_batch` function that I'm using in the hook_install/updates.

**Comment by lhridley** [comment]
Good job!  Merging...

**Pull request merged**
