### PR TITLE
Issue #40: Create "Contact Us" Form

### PR DESCRIPTION
**Pull request by lrowang**
Hi @lhridley - 

PR for #40 ready for official review!
- Created the "Contact Form" category and saved it via a new Feature
- Created a new Behat test suite to verify access and form submissions for the contact form
- Updated each role's permissions (and the corresponding behat tests). A note about the permissions, the book didn't specify who gets what, so I made a call to:
  - Keep the permission related to configuring the form restricted to "site administrator"
  - Allow everyone the ability to submit the form
  - Restrict the ability to use personal user's contact forms to "authenticated users" and above.

Here's a screen shot of what I selected -- **would you agree with those permissions**?
cs 40-permissions

### CODE REVIEW

**Comment by lrowang** [comment]
Ha! Good thing for Travis tests! I totally forgot to enable the new feature module I created for the contact category! It's there now and both local and travis are passing!

**Comment by lhridley** [comment]
The users don't need a contact form, so that can be disabled for authenticated users.  Only enable that permission for site administrators.

You should write a test that tests submitting the form without having all the required fields filled out, so you can test for the proper error messages.

**Comment by lrowang** [comment]
Hi @lhridley -

I pushed the commits that I've made since we discussed this morning. I broke them up as granularly as I could after I restricted the "Use user's personal contact forms" permissions. Hopefully we can identify what's causing the `response status code 403` failures that weren't there before!

**Comment by lhridley** [comment]
@ro  I pushed corrections to your behat configuration and a few tweaks to your tests this morning.  I'm going to merge this into the develop branch, but let's discuss these changes on our call today.

**Pull request merged**
